#ifndef PINOUTS_H
#define PINOUTS_H

#define PIN_BITMASK(pin_num) (1ULL << pin_num)

#define LED_STATUS_PIN 2

#define ULTRASONIC_TRIG_PIN 19
#define ULTRASONIC_ECHO_PIN 18

#define HOMING_LIM_SWCH_PIN 17
#define ARM1_INNER_LIM_SWCH_PIN 27
#define ARM1_OUTER_LIM_SWCH_PIN 14
#define ARM2_INNER_LIM_SWCH_PIN 12
#define ARM2_OUTER_LIM_SWCH_PIN 13
#define ARM3_INNER_LIM_SWCH_PIN 16
#define ARM3_OUTER_LIM_SWCH_PIN 0

#define I2C_MASTER_SDA_PIN 21
#define I2C_MASTER_SCL_PIN 22
#define I2C_MASTER_FREQ_HZ 100000

#define PCA9685_OUTPUT_ENABLED_PIN 5

#endif